[tool.poetry]
name = "Image manip"
version = "0.0.1"
description = ""
authors = ["Mikołaj Badyl <contact@hawier.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
